In [17]:
import pandas as pd
import numpy as np
df = pd.read_csv('serie_temporal_suave.csv')
df

       x    y
0      1  551
1      2  559
2      3  588
3      4  617
4      5  637
..   ...  ...
495  496  369
496  497  384
497  498  398
498  499  422
499  500  435

[500 rows x 2 columns]

In [18]:
df_adicao = df
df_adicao

       x    y
0      1  551
1      2  559
2      3  588
3      4  617
4      5  637
..   ...  ...
495  496  369
496  497  384
497  498  398
498  499  422
499  500  435

[500 rows x 2 columns]

In [23]:
df_adicao['a'] = np.random.randint(0, 2001, size=len(df_adicao))
df_adicao['b'] = np.random.randint(0, 2001, size=len(df_adicao))
df_adicao['e'] = np.random.randint(0, 2001, size=len(df_adicao))
df_adicao['f'] = np.random.randint(0, 2001, size=len(df_adicao))

In [24]:
df_adicao

       x    y     a     b     e     f
0      1  551   828  1773   736   398
1      2  559   795   381   849  1579
2      3  588  1254   969  1868   688
3      4  617   273  1176   726   871
4      5  637   469   429   228  1690
..   ...  ...   ...   ...   ...   ...
495  496  369  1072   529   805   611
496  497  384   444   267  1713  1406
497  498  398  1411   674  1146    36
498  499  422    66   320  1493   988
499  500  435    96  1534   317  1975

[500 rows x 6 columns]

In [ ]:
df_adicao.to_csv('serie_temporal_suave2.csv')