In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("automoveis_dados.csv")

In [2]:
display(df)

,nivel_risco,perdas_normalizadas,marca,tipo_combustivel,aspiracao,numero_portas,tipo_carroceria,tracao,local_motor,distancia_eixos,...,tamanho_motor,sistema_combustivel,diametro_cilindro,curso_pistao,taxa_compressao,potencia,rpm_maximo,consumo_cidade_mpg,consumo_estrada_mpg,preco
0,3,?,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gasolina,padrao,duas,hatchback,traseira,frontal,94.5,...,152,injecao_multiponto,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gasolina,padrao,quatro,sedan,dianteira,frontal,99.8,...,109,injecao_multiponto,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gasolina,padrao,quatro,sedan,quatro_por_quatro,frontal,99.4,...,136,injecao_multiponto,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,173,injecao_multiponto,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,quatro,sedan,traseira,frontal,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,19,25,22625

In [3]:
df.shape

(205, 26)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   nivel_risco          205 non-null    int64
 1   perdas_normalizadas  205 non-null    object
 2   marca                205 non-null    object
 3   tipo_combustivel     205 non-null    object
 4   aspiracao            205 non-null    object
 5   numero_portas        205 non-null    object
 6   tipo_carroceria      205 non-null    object
 7   tracao               205 non-null    object
 8   local_motor          205 non-null    object
 9   distancia_eixos      205 non-null    float64
 10  comprimento          205 non-null    float64
 11  largura              205 non-null    float64
 12  altura               205 non-null    float64
 13  peso                 205 non-null    int64
 14  tipo_motor           205 non-null    object
 15  numero_cilindros     205 non-null    object
 16  tamanho_motor        205 non-null    int64
 17  sistema_combustivel  205 non-null    object
 18  diametro_cilindro    205 non-null    object
 19  curso_pistao         205 non-null    object
 20  taxa_compressao      205 non-null    float64
 21  potencia             205 non-null    object
 22  rpm_maximo           205 non-null    object
 23  consumo_cidade_mpg   205 non-null    int64
 24  consumo_estrada_mpg  205 non-null    int64
 25  preco                205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [5]:
df_tratamento = df

In [6]:
df_tratamento

,nivel_risco,perdas_normalizadas,marca,tipo_combustivel,aspiracao,numero_portas,tipo_carroceria,tracao,local_motor,distancia_eixos,...,tamanho_motor,sistema_combustivel,diametro_cilindro,curso_pistao,taxa_compressao,potencia,rpm_maximo,consumo_cidade_mpg,consumo_estrada_mpg,preco
0,3,?,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gasolina,padrao,duas,hatchback,traseira,frontal,94.5,...,152,injecao_multiponto,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gasolina,padrao,quatro,sedan,dianteira,frontal,99.8,...,109,injecao_multiponto,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gasolina,padrao,quatro,sedan,quatro_por_quatro,frontal,99.4,...,136,injecao_multiponto,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,173,injecao_multiponto,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,quatro,sedan,traseira,frontal,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,19,25,22625

In [7]:
df_tratamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   nivel_risco          205 non-null    int64
 1   perdas_normalizadas  205 non-null    object
 2   marca                205 non-null    object
 3   tipo_combustivel     205 non-null    object
 4   aspiracao            205 non-null    object
 5   numero_portas        205 non-null    object
 6   tipo_carroceria      205 non-null    object
 7   tracao               205 non-null    object
 8   local_motor          205 non-null    object
 9   distancia_eixos      205 non-null    float64
 10  comprimento          205 non-null    float64
 11  largura              205 non-null    float64
 12  altura               205 non-null    float64
 13  peso                 205 non-null    int64
 14  tipo_motor           205 non-null    object
 15  numero_cilindros     205 non-null    object
 16  tamanho_motor        205 non-null    int64
 17  sistema_combustivel  205 non-null    object
 18  diametro_cilindro    205 non-null    object
 19  curso_pistao         205 non-null    object
 20  taxa_compressao      205 non-null    float64
 21  potencia             205 non-null    object
 22  rpm_maximo           205 non-null    object
 23  consumo_cidade_mpg   205 non-null    int64
 24  consumo_estrada_mpg  205 non-null    int64
 25  preco                205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [8]:
df_tratamento["perdas_normalizadas"] = df_tratamento["perdas_normalizadas"].replace("?", np.nan)
df_tratamento

,nivel_risco,perdas_normalizadas,marca,tipo_combustivel,aspiracao,numero_portas,tipo_carroceria,tracao,local_motor,distancia_eixos,...,tamanho_motor,sistema_combustivel,diametro_cilindro,curso_pistao,taxa_compressao,potencia,rpm_maximo,consumo_cidade_mpg,consumo_estrada_mpg,preco
0,3,NaN,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gasolina,padrao,duas,hatchback,traseira,frontal,94.5,...,152,injecao_multiponto,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gasolina,padrao,quatro,sedan,dianteira,frontal,99.8,...,109,injecao_multiponto,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gasolina,padrao,quatro,sedan,quatro_por_quatro,frontal,99.4,...,136,injecao_multiponto,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,173,injecao_multiponto,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,quatro,sedan,traseira,frontal,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,19,25,22625

In [9]:
df_tratamento["perdas_normalizadas"] = pd.to_numeric(df_tratamento["perdas_normalizadas"])
df_tratamento

,nivel_risco,perdas_normalizadas,marca,tipo_combustivel,aspiracao,numero_portas,tipo_carroceria,tracao,local_motor,distancia_eixos,...,tamanho_motor,sistema_combustivel,diametro_cilindro,curso_pistao,taxa_compressao,potencia,rpm_maximo,consumo_cidade_mpg,consumo_estrada_mpg,preco
0,3,NaN,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gasolina,padrao,duas,hatchback,traseira,frontal,94.5,...,152,injecao_multiponto,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164.0,audi,gasolina,padrao,quatro,sedan,dianteira,frontal,99.8,...,109,injecao_multiponto,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164.0,audi,gasolina,padrao,quatro,sedan,quatro_por_quatro,frontal,99.4,...,136,injecao_multiponto,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95.0,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95.0,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,173,injecao_multiponto,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95.0,volvo,diesel,turbo,quatro,sedan,traseira,frontal,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95.0,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
df_tratamento["perdas_normalizadas"].median()

np.float64(115.0)

In [11]:
df_tratamento["perdas_normalizadas"] = df_tratamento["perdas_normalizadas"].fillna(df_tratamento["perdas_normalizadas"].median())
df_tratamento

,nivel_risco,perdas_normalizadas,marca,tipo_combustivel,aspiracao,numero_portas,tipo_carroceria,tracao,local_motor,distancia_eixos,...,tamanho_motor,sistema_combustivel,diametro_cilindro,curso_pistao,taxa_compressao,potencia,rpm_maximo,consumo_cidade_mpg,consumo_estrada_mpg,preco
0,3,115.0,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,13495
1,3,115.0,alfa-romero,gasolina,padrao,duas,conversivel,traseira,frontal,88.6,...,130,injecao_multiponto,3.47,2.68,9.0,111,5000,21,27,16500
2,1,115.0,alfa-romero,gasolina,padrao,duas,hatchback,traseira,frontal,94.5,...,152,injecao_multiponto,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164.0,audi,gasolina,padrao,quatro,sedan,dianteira,frontal,99.8,...,109,injecao_multiponto,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164.0,audi,gasolina,padrao,quatro,sedan,quatro_por_quatro,frontal,99.4,...,136,injecao_multiponto,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95.0,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95.0,volvo,gasolina,padrao,quatro,sedan,traseira,frontal,109.1,...,173,injecao_multiponto,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95.0,volvo,diesel,turbo,quatro,sedan,traseira,frontal,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95.0,volvo,gasolina,turbo,quatro,sedan,traseira,frontal,109.1,...,141,injecao_multiponto,3.78,3.15,9.5,114,5400,19,25,22625

In [12]:
df_tratamento["preco"] = df_tratamento["preco"].replace("?", np.nan)
df_tratamento["preco"] = pd.to_numeric(df_tratamento["preco"])

In [13]:
df_tratamento["potencia"] = df_tratamento["potencia"].replace("?", np.nan)
df_tratamento["potencia"] = pd.to_numeric(df_tratamento["potencia"])
df_tratamento["potencia"] = df_tratamento["potencia"].fillna(df_tratamento["potencia"].median())

In [14]:
df_tratamento["numero_portas"] = df_tratamento["numero_portas"].replace("?", np.nan)
df_tratamento["numero_portas"] = df_tratamento["numero_portas"].fillna("quatro")

In [15]:
df_tratamento["diametro_cilindro"] = df_tratamento["diametro_cilindro"].replace("?", np.nan)
df_tratamento["diametro_cilindro"] = pd.to_numeric(df_tratamento["diametro_cilindro"])
df_tratamento["diametro_cilindro"] = df_tratamento["diametro_cilindro"].fillna(df_tratamento["diametro_cilindro"].median())

In [16]:
df_tratamento["curso_pistao"] = df_tratamento["curso_pistao"].replace("?", np.nan)
df_tratamento["curso_pistao"] = pd.to_numeric(df_tratamento["curso_pistao"])
df_tratamento["curso_pistao"] = df_tratamento["curso_pistao"].fillna(df_tratamento["diametro_cilindro"].median())

In [17]:
df_tratamento["rpm_maximo"] = df_tratamento["rpm_maximo"].replace("?", np.nan)
df_tratamento["rpm_maximo"] = pd.to_numeric(df_tratamento["rpm_maximo"])
df_tratamento["rpm_maximo"] = df_tratamento["rpm_maximo"].fillna(df_tratamento["rpm_maximo"].median())

In [ ]:
df_tratamento.to_csv("concessionaria_carros.csv")