In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel('covid.xlsx')
df

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab)
0,AC,Acrelândia,15256,0,3802,-,0,40,O cálculo requer população >= a 100.000 hab
1,AC,Assis Brasil,7417,0,2383,-,0,27,O cálculo requer população >= a 100.000 hab
2,AC,Brasiléia,26278,2,4391,-,0,53,O cálculo requer população >= a 100.000 hab
3,AC,Bujari,10266,1,1701,-,0,21,O cálculo requer população >= a 100.000 hab
4,AC,Capixaba,11733,0,1242,-,0,20,O cálculo requer população >= a 100.000 hab
...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,-,0,61,O cálculo requer população >= a 100.000 hab
5587,TO,Tupirama,1891,0,476,-,0,4,O cálculo requer população >= a 100.000 hab
5588,TO,Tupiratins,2671,0,447,-,0,3,O cálculo requer população >= a 100.000 hab
5589,TO,Wanderlândia,11683,0,2686,-,0,24,O cálculo requer população >= a 100.000 hab
5590,TO,Xambioá,11540,0,2964,-,0,42,O cálculo requer população >= a 100.000 hab

In [2]:
df_tratamento = df
df_tratamento

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab)
0,AC,Acrelândia,15256,0,3802,-,0,40,O cálculo requer população >= a 100.000 hab
1,AC,Assis Brasil,7417,0,2383,-,0,27,O cálculo requer população >= a 100.000 hab
2,AC,Brasiléia,26278,2,4391,-,0,53,O cálculo requer população >= a 100.000 hab
3,AC,Bujari,10266,1,1701,-,0,21,O cálculo requer população >= a 100.000 hab
4,AC,Capixaba,11733,0,1242,-,0,20,O cálculo requer população >= a 100.000 hab
...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,-,0,61,O cálculo requer população >= a 100.000 hab
5587,TO,Tupirama,1891,0,476,-,0,4,O cálculo requer população >= a 100.000 hab
5588,TO,Tupiratins,2671,0,447,-,0,3,O cálculo requer população >= a 100.000 hab
5589,TO,Wanderlândia,11683,0,2686,-,0,24,O cálculo requer população >= a 100.000 hab
5590,TO,Xambioá,11540,0,2964,-,0,42,O cálculo requer população >= a 100.000 hab

In [3]:
df_tratamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5591 entries, 0 to 5590
Data columns (total 9 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   UF                                                 5591 non-null   object
 1   Município                                          5570 non-null   object
 2   População                                          5591 non-null   int64
 3   Casos novos notificados na semana epidemiológica   5591 non-null   int64
 4   Casos Acumulados                                   5591 non-null   int64
 5   Incidência covid-19 (100 mil hab)                  5591 non-null   object
 6   Óbitos novos notificados na semana epidemiológica  5591 non-null   int64
 7   Óbitos Acumulados                                  5591 non-null   int64
 8   Taxa mortalidade (100 mil hab)                     5591 non-null   object
dtypes: int64(5), object(4)
memory usage: 393.2+ KB

#### Transformando os valores "-" da coluna "Incidência covid-19 (100 mil hab)" em "NaN"

In [4]:
df_tratamento['Incidência covid-19 (100 mil hab)'] = df_tratamento['Incidência covid-19 (100 mil hab)'].replace('-', np.nan)
df_tratamento

/tmp/ipykernel_16823/1034750861.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_tratamento['Incidência covid-19 (100 mil hab)'] = df_tratamento['Incidência covid-19 (100 mil hab)'].replace('-', np.nan)

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab)
0,AC,Acrelândia,15256,0,3802,NaN,0,40,O cálculo requer população >= a 100.000 hab
1,AC,Assis Brasil,7417,0,2383,NaN,0,27,O cálculo requer população >= a 100.000 hab
2,AC,Brasiléia,26278,2,4391,NaN,0,53,O cálculo requer população >= a 100.000 hab
3,AC,Bujari,10266,1,1701,NaN,0,21,O cálculo requer população >= a 100.000 hab
4,AC,Capixaba,11733,0,1242,NaN,0,20,O cálculo requer população >= a 100.000 hab
...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,NaN,0,61,O cálculo requer população >= a 100.000 hab
5587,TO,Tupirama,1891,0,476,NaN,0,4,O cálculo requer população >= a 100.000 hab
5588,TO,Tupiratins,2671,0,447,NaN,0,3,O cálculo requer população >= a 100.000 hab
5589,TO,Wanderlândia,11683,0,2686,NaN,0,24,O cálculo requer população >= a 100.000 hab
5590,TO,Xambioá,11540,0,2964,NaN,0,42,O cálculo requer população >= a 100.000 hab

In [5]:
df_tratamento['Incidência covid-19 (100 mil hab)'] = pd.to_numeric(df_tratamento['Incidência covid-19 (100 mil hab)'])
df_tratamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5591 entries, 0 to 5590
Data columns (total 9 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   UF                                                 5591 non-null   object
 1   Município                                          5570 non-null   object
 2   População                                          5591 non-null   int64
 3   Casos novos notificados na semana epidemiológica   5591 non-null   int64
 4   Casos Acumulados                                   5591 non-null   int64
 5   Incidência covid-19 (100 mil hab)                  324 non-null    float64
 6   Óbitos novos notificados na semana epidemiológica  5591 non-null   int64
 7   Óbitos Acumulados                                  5591 non-null   int64
 8   Taxa mortalidade (100 mil hab)                     5591 non-null   object
dtypes: float64(1), int64(5), object(3)
memory usage: 393.2+ KB

#### Arrumando os valores da coluna "Incidência covid-19 (100 mil hab)"

In [6]:
df_tratamento['Taxa mortalidade (100 mil hab)'] = df_tratamento['Taxa mortalidade (100 mil hab)'].replace('O cálculo requer população >= a 100.000 hab', np.nan)
df_tratamento

/tmp/ipykernel_16823/963235032.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_tratamento['Taxa mortalidade (100 mil hab)'] = df_tratamento['Taxa mortalidade (100 mil hab)'].replace('O cálculo requer população >= a 100.000 hab', np.nan)

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab)
0,AC,Acrelândia,15256,0,3802,NaN,0,40,NaN
1,AC,Assis Brasil,7417,0,2383,NaN,0,27,NaN
2,AC,Brasiléia,26278,2,4391,NaN,0,53,NaN
3,AC,Bujari,10266,1,1701,NaN,0,21,NaN
4,AC,Capixaba,11733,0,1242,NaN,0,20,NaN
...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,NaN,0,61,NaN
5587,TO,Tupirama,1891,0,476,NaN,0,4,NaN
5588,TO,Tupiratins,2671,0,447,NaN,0,3,NaN
5589,TO,Wanderlândia,11683,0,2686,NaN,0,24,NaN
5590,TO,Xambioá,11540,0,2964,NaN,0,42,NaN

In [7]:
df_tratamento['Taxa mortalidade (100 mil hab)'] = pd.to_numeric(df_tratamento['Taxa mortalidade (100 mil hab)'])
df_tratamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5591 entries, 0 to 5590
Data columns (total 9 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   UF                                                 5591 non-null   object
 1   Município                                          5570 non-null   object
 2   População                                          5591 non-null   int64
 3   Casos novos notificados na semana epidemiológica   5591 non-null   int64
 4   Casos Acumulados                                   5591 non-null   int64
 5   Incidência covid-19 (100 mil hab)                  324 non-null    float64
 6   Óbitos novos notificados na semana epidemiológica  5591 non-null   int64
 7   Óbitos Acumulados                                  5591 non-null   int64
 8   Taxa mortalidade (100 mil hab)                     324 non-null    float64
dtypes: float64(2), int64(5), object(2)
memory usage: 393.2+ KB

#### Criando Novas Colunas

In [ ]:
df_tratamento['Letalidade (%)'] = np.where(df_tratamento['Casos Acumulados'] == 0, np.nan, ((df_tratamento['Óbitos Acumulados'] / df_tratamento['Casos Acumulados'] * 100)))
df_tratamento

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab),Letalidade (%)
0,AC,Acrelândia,15256,0,3802,NaN,0,40,NaN,1.052078
1,AC,Assis Brasil,7417,0,2383,NaN,0,27,NaN,1.133026
2,AC,Brasiléia,26278,2,4391,NaN,0,53,NaN,1.207014
3,AC,Bujari,10266,1,1701,NaN,0,21,NaN,1.234568
4,AC,Capixaba,11733,0,1242,NaN,0,20,NaN,1.610306
...,...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,NaN,0,61,NaN,1.295667
5587,TO,Tupirama,1891,0,476,NaN,0,4,NaN,0.840336
5588,TO,Tupiratins,2671,0,447,NaN,0,3,NaN,0.671141
5589,TO,Wanderlândia,11683,0,2686,NaN,0,24,NaN,0.893522
5590,TO,Xambioá,11540,0,2964,NaN,0,42,NaN,1.417004

In [11]:
df_tratamento[' Casos por 100 mil (recalc)'] = (df_tratamento['Casos Acumulados'] / df_tratamento['População']) * 100000
df_tratamento

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab),Letalidade (%),Casos por 100 mil (recalc)
0,AC,Acrelândia,15256,0,3802,NaN,0,40,NaN,1.052078,24921.342423
1,AC,Assis Brasil,7417,0,2383,NaN,0,27,NaN,1.133026,32128.893083
2,AC,Brasiléia,26278,2,4391,NaN,0,53,NaN,1.207014,16709.795266
3,AC,Bujari,10266,1,1701,NaN,0,21,NaN,1.234568,16569.257744
4,AC,Capixaba,11733,0,1242,NaN,0,20,NaN,1.610306,10585.527998
...,...,...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,NaN,0,61,NaN,1.295667,20585.920420
5587,TO,Tupirama,1891,0,476,NaN,0,4,NaN,0.840336,25171.866737
5588,TO,Tupiratins,2671,0,447,NaN,0,3,NaN,0.671141,16735.305129
5589,TO,Wanderlândia,11683,0,2686,NaN,0,24,NaN,0.893522,22990.670205
5590,TO,Xambioá,11540,0,2964,NaN,0,42,NaN,1.417004,25684.575390

In [13]:
df_tratamento['Óbitos por 100 mil (recalc)'] = (df_tratamento['Óbitos Acumulados'] / df_tratamento['População']) * 100000
df_tratamento

,UF,Município,População,Casos novos notificados na semana epidemiológica,Casos Acumulados,Incidência covid-19 (100 mil hab),Óbitos novos notificados na semana epidemiológica,Óbitos Acumulados,Taxa mortalidade (100 mil hab),Letalidade (%),Casos por 100 mil (recalc),Óbitos por 100 mil (recalc)
0,AC,Acrelândia,15256,0,3802,NaN,0,40,NaN,1.052078,24921.342423,262.191924
1,AC,Assis Brasil,7417,0,2383,NaN,0,27,NaN,1.133026,32128.893083,364.028583
2,AC,Brasiléia,26278,2,4391,NaN,0,53,NaN,1.207014,16709.795266,201.689626
3,AC,Bujari,10266,1,1701,NaN,0,21,NaN,1.234568,16569.257744,204.558738
4,AC,Capixaba,11733,0,1242,NaN,0,20,NaN,1.610306,10585.527998,170.459388
...,...,...,...,...,...,...,...,...,...,...,...,...
5586,TO,Tocantinópolis,22870,0,4708,NaN,0,61,NaN,1.295667,20585.920420,266.724967
5587,TO,Tupirama,1891,0,476,NaN,0,4,NaN,0.840336,25171.866737,211.528292
5588,TO,Tupiratins,2671,0,447,NaN,0,3,NaN,0.671141,16735.305129,112.317484
5589,TO,Wanderlândia,11683,0,2686,NaN,0,24,NaN,0.893522,22990.670205,205.426688
5590,TO,Xambioá,11540,0,2964,NaN,0,42,NaN,1.417004,25684.575390,363.951473

In [ ]:
df_tratamento.to_csv('parte_b.csv')